# Static Folder Path
STATIC_FOLDER = 'static-build'
STATIC_FOLDER_DEBUG = 'static'

# User paginate
USER_FOLLOWERS_PER_PAGE = 2
USER_FOLLOWING_PER_PAGE = 2
USER_PER_PAGE = 20
FILTER_USER_LIMIT = 20

# Role paginate
ROLE_PER_PAGE = 20