DB_TYPE = 'mysql'
DB_USER_ID = 'root'
DB_USER_PASSWORD = ''
DB_HOST_NAME = 'localhost'
DB_NAME = 'fcib_dev'
DATABASE_QUERY_TIMEOUT = 0.7
SQLALCHEMY_DATABASE_URI = DB_TYPE+'://'+DB_USER_ID+':'+DB_USER_PASSWORD+'@'+DB_HOST_NAME+'/'+DB_NAME